import type { Recipe } from "./types"

export const recipeDatabase: Recipe[] = [
  {
    id: "r1",
    title: "Creamy Lemon Chicken Pasta",
    description: "A rich and creamy pasta dish with tender chicken thighs and bright lemon flavor",
    image: "/creamy-lemon-chicken-pasta-dish.png",
    ingredients: [
      { name: "chicken thighs", quantity: 500, unit: "g", category: "protein" },
      { name: "pasta", quantity: 300, unit: "g", category: "grains" },
      { name: "lemon", quantity: 1, unit: "pieces", substitutions: ["lime"], category: "fruits" },
      {
        name: "greek yogurt",
        quantity: 150,
        unit: "g",
        substitutions: ["sour cream", "heavy cream"],
        category: "dairy",
      },
      { name: "garlic", quantity: 3, unit: "cloves", category: "vegetables" },
      { name: "olive oil", quantity: 2, unit: "tbsp", category: "other" },
      { name: "parmesan cheese", quantity: 50, unit: "g", optional: true, category: "dairy" },
      {
        name: "fresh herbs",
        quantity: 2,
        unit: "tbsp",
        optional: true,
        substitutions: ["dried herbs"],
        category: "other",
      },
    ],
    instructions: [
      "Season chicken thighs with salt and pepper",
      "Heat olive oil in a large pan over medium-high heat",
      "Cook chicken until golden brown and cooked through, about 6-8 minutes per side",
      "Remove chicken and set aside, slice when cool enough to handle",
      "Cook pasta according to package directions until al dente",
      "In the same pan, sauté minced garlic for 1 minute",
      "Add cooked pasta, sliced chicken, and greek yogurt",
      "Toss with lemon juice and zest",
      "Garnish with parmesan and fresh herbs if using",
    ],
    timeTotal: 28,
    timeActive: 20,
    skillRequired: 2,
    cookwareRequired: ["large pan", "pot"],
    servings: 4,
    nutrition: {
      calories: 650,
      protein: 48,
      carbs: 55,
      fat: 22,
    },
    dietaryFlags: ["contains_gluten", "contains_dairy"],
    tags: ["comfort food", "weeknight dinner", "high protein"],
    cuisine: "Italian-inspired",
    source: "PantryMatch",
    rating: 4.7,
    reviewCount: 234,
  },
  {
    id: "r2",
    title: "Mediterranean Stuffed Bell Peppers",
    description: "Colorful bell peppers stuffed with a savory mixture of rice, vegetables, and herbs",
    image: "/mediterranean-stuffed-bell-peppers-with-rice.png",
    ingredients: [
      { name: "bell peppers", quantity: 4, unit: "pieces", category: "vegetables" },
      { name: "rice", quantity: 200, unit: "g", substitutions: ["quinoa", "couscous"], category: "grains" },
      { name: "onion", quantity: 1, unit: "pieces", category: "vegetables" },
      { name: "tomatoes", quantity: 2, unit: "pieces", category: "vegetables" },
      { name: "feta cheese", quantity: 100, unit: "g", optional: true, category: "dairy" },
      { name: "olive oil", quantity: 3, unit: "tbsp", category: "other" },
      { name: "garlic", quantity: 2, unit: "cloves", category: "vegetables" },
      { name: "fresh herbs", quantity: 3, unit: "tbsp", substitutions: ["dried herbs"], category: "other" },
    ],
    instructions: [
      "Preheat oven to 375°F (190°C)",
      "Cut tops off bell peppers and remove seeds and membranes",
      "Cook rice according to package directions",
      "Sauté diced onion and garlic in olive oil until softened",
      "Add diced tomatoes and cook for 5 minutes",
      "Mix cooked rice with sautéed vegetables and herbs",
      "Stuff peppers with rice mixture and top with feta if using",
      "Bake for 25-30 minutes until peppers are tender",
    ],
    timeTotal: 45,
    timeActive: 20,
    skillRequired: 2,
    cookwareRequired: ["oven", "baking dish", "pan"],
    servings: 4,
    nutrition: {
      calories: 320,
      protein: 12,
      carbs: 52,
      fat: 8,
    },
    dietaryFlags: ["vegetarian", "gluten_free"],
    tags: ["healthy", "vegetarian", "meal prep"],
    cuisine: "Mediterranean",
    source: "PantryMatch",
    rating: 4.5,
    reviewCount: 189,
  },
  {
    id: "r3",
    title: "Quick Chicken Stir-Fry",
    description: "Fast and flavorful stir-fry with chicken and fresh vegetables",
    image: "/chicken-stir-fry-with-vegetables-in-wok.png",
    ingredients: [
      { name: "chicken breast", quantity: 400, unit: "g", substitutions: ["chicken thighs"], category: "protein" },
      { name: "bell peppers", quantity: 2, unit: "pieces", category: "vegetables" },
      { name: "broccoli", quantity: 200, unit: "g", substitutions: ["snap peas", "carrots"], category: "vegetables" },
      { name: "soy sauce", quantity: 3, unit: "tbsp", category: "other" },
      { name: "garlic", quantity: 3, unit: "cloves", category: "vegetables" },
      { name: "ginger", quantity: 1, unit: "tbsp", optional: true, category: "other" },
      { name: "vegetable oil", quantity: 2, unit: "tbsp", category: "other" },
      { name: "rice", quantity: 200, unit: "g", optional: true, category: "grains" },
    ],
    instructions: [
      "Cut chicken into bite-sized pieces",
      "Heat oil in a wok or large pan over high heat",
      "Stir-fry chicken until cooked through, about 5-6 minutes",
      "Add garlic and ginger, stir for 30 seconds",
      "Add vegetables and stir-fry for 3-4 minutes until crisp-tender",
      "Add soy sauce and toss to combine",
      "Serve over rice if using",
    ],
    timeTotal: 15,
    timeActive: 15,
    skillRequired: 2,
    cookwareRequired: ["wok", "pot"],
    servings: 3,
    nutrition: {
      calories: 380,
      protein: 35,
      carbs: 25,
      fat: 12,
    },
    dietaryFlags: ["gluten_free", "dairy_free"],
    tags: ["quick", "healthy", "high protein"],
    cuisine: "Asian-inspired",
    source: "PantryMatch",
    rating: 4.6,
    reviewCount: 312,
  },
  {
    id: "r4",
    title: "Greek Yogurt Parfait Bowl",
    description: "Healthy and refreshing parfait with layers of yogurt, fruits, and granola",
    image: "/greek-yogurt-parfait-bowl-with-berries-and-granola.png",
    ingredients: [
      { name: "greek yogurt", quantity: 300, unit: "g", category: "dairy" },
      { name: "berries", quantity: 150, unit: "g", substitutions: ["any fresh fruit"], category: "fruits" },
      { name: "granola", quantity: 60, unit: "g", optional: true, category: "other" },
      { name: "honey", quantity: 2, unit: "tbsp", optional: true, substitutions: ["maple syrup"], category: "other" },
      { name: "nuts", quantity: 30, unit: "g", optional: true, category: "other" },
    ],
    instructions: [
      "Layer half the yogurt in serving bowls",
      "Add half the berries and a drizzle of honey",
      "Add remaining yogurt",
      "Top with remaining berries, granola, and nuts",
      "Drizzle with remaining honey if desired",
    ],
    timeTotal: 5,
    timeActive: 5,
    skillRequired: 1,
    cookwareRequired: ["bowls"],
    servings: 2,
    nutrition: {
      calories: 280,
      protein: 20,
      carbs: 35,
      fat: 8,
    },
    dietaryFlags: ["vegetarian", "gluten_free"],
    tags: ["breakfast", "healthy", "no cook", "high protein"],
    cuisine: "International",
    source: "PantryMatch",
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: "r5",
    title: "Spicy Pasta Arrabbiata",
    description: "Classic Italian pasta with a spicy tomato sauce and fresh herbs",
    image: "/spicy-pasta-arrabbiata-with-red-pepper-flakes.png",
    ingredients: [
      { name: "pasta", quantity: 400, unit: "g", category: "grains" },
      { name: "canned tomatoes", quantity: 400, unit: "g", substitutions: ["fresh tomatoes"], category: "vegetables" },
      { name: "garlic", quantity: 4, unit: "cloves", category: "vegetables" },
      { name: "red pepper flakes", quantity: 1, unit: "tsp", category: "spices" },
      { name: "olive oil", quantity: 4, unit: "tbsp", category: "other" },
      { name: "fresh basil", quantity: 10, unit: "leaves", optional: true, category: "other" },
      { name: "parmesan cheese", quantity: 50, unit: "g", optional: true, category: "dairy" },
    ],
    instructions: [
      "Cook pasta according to package directions until al dente",
      "Heat olive oil in a large pan over medium heat",
      "Add minced garlic and red pepper flakes, cook for 1 minute",
      "Add crushed tomatoes and simmer for 10 minutes",
      "Season with salt and pepper",
      "Toss cooked pasta with sauce",
      "Garnish with fresh basil and parmesan if using",
    ],
    timeTotal: 20,
    timeActive: 15,
    skillRequired: 2,
    cookwareRequired: ["pot", "large pan"],
    servings: 4,
    nutrition: {
      calories: 420,
      protein: 14,
      carbs: 78,
      fat: 8,
    },
    dietaryFlags: ["vegetarian", "vegan_option"],
    tags: ["spicy", "italian", "comfort food"],
    cuisine: "Italian",
    source: "PantryMatch",
    rating: 4.4,
    reviewCount: 278,
  },
]
